"""create tables

Revision ID: 8080a115be23
Revises: a5403c1f0b07
Create Date: 2023-10-20 11:33:40.897886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8080a115be23'
down_revision: Union[str, None] = 'a5403c1f0b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('isAdmin', sa.Boolean(), nullable=False),
                    sa.Column('balance', sa.Double(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('transports',
                    sa.Column('ownerId', sa.Integer(), nullable=False),
                    sa.Column('canBeRented', sa.Boolean(), nullable=False),
                    sa.Column('transportType', sa.String(), nullable=False),
                    sa.Column('model', sa.String(), nullable=False),
                    sa.Column('color', sa.String(), nullable=False),
                    sa.Column('identifier', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('latitude', sa.Double(), nullable=False),
                    sa.Column('longitude', sa.Double(), nullable=False),
                    sa.Column('minutePrice', sa.Double(), nullable=False),
                    sa.Column('dayPrice', sa.Double(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('rents',
                    sa.Column('userId', sa.Integer(), nullable=False),
                    sa.Column('transportId', sa.Integer(), nullable=False),
                    sa.Column('timeStart', sa.TIMESTAMP(), nullable=False),
                    sa.Column('timeEnd', sa.TIMESTAMP(), nullable=True),
                    sa.Column('priceOfUnit', sa.Double(), nullable=False),
                    sa.Column('priceType', sa.String(), nullable=False),
                    sa.Column('finalPrice', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['transportId'], ['transports.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rents')
    op.drop_table('transports')
    op.drop_table('users')
    # ### end Alembic commands ###
